# 16811A0556

## Question -1:
write a program to print the next character of given string except z(z is same as z)
- Input Format:
hello
- Output Format:
ifmmp

In [2]:
s=input()
for r in s:
    if r.isalpha():
        if r=='z':
            print(r)
        else:
            print(chr(ord(r)+1),end='')
    else:
        print(r,end='')

hello
ifmmp

In [3]:
import numpy as np
li=([1.,2.,3.,4.])
a= np.array(li)
a

array([1., 2., 3., 4.])

- for example the following code print 1D array between 1 to 15 

In [6]:
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- for example the following code print 1000 numbers in a 1D array

In [9]:
import numpy as np
a2=np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [11]:
a2=np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [14]:
import numpy as np
array1=np.random.randint(0,2,size=(3,3))
array1[2][2]
print('shape:',array1.shape)
print('size:',array1.size)
print('DType:',array1.dtype)
print('Itemsize:',array1.itemsize)
print('Data:',array1.data)
array1

shape: (3, 3)
size: 9
DType: int32
Itemsize: 4
Data: <memory at 0x00000282A41A6990>


array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 0]])

In [17]:
import numpy as np
a= np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
np.ones?

In [19]:
b=[[1,2,3,],[10,20,30],[11,22,33]]
c=np.array(b)
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

In [20]:
d=c+1
d

array([[ 2,  3,  4],
       [11, 21, 31],
       [12, 23, 34]])

- we can perform arithmetic operatords in Numpy like addition,subtraction etc..,and of course,log,sin,cos,etc

In [21]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(5,11).reshape(2,3)
print(a,)
print(b,'\n')
print(a+b)
print(a/b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]] 

[[ 6  8 10]
 [12 14 16]]
[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


a=91,2,3