## Data Encryption and Decryption

- Data Encrytion
                 Encryption is a security method in which information is a ncoded in such a way that only authorized user can read it.It uses encryption algorithm to generate ciphertext that can only be read if decrypted.
- Data Decryption
                Decryption is the process of taking encoded or encrypted text and convertion it back into text that you or the computer can read and understand
- Types
        symmetric (private key):It uses a single key that will be shared among the people who need to receive the message
- Asymmetric (Public key):
                        Asymmetrical encryption uses a pair of public key and a private key to encrypt and decrypt messages
- write a function to generate key for encryption


In [13]:
# Function to generate key for encryption
keypath='DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w')as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+' '+str(i+4)+'\n')
            else:
                f.write(str(i)+' '+str(i-6)+'\n')
    return
generatekey(keypath)

In [18]:
# Function to decrypt a datafile
keyfile='DataFiles/key.txt'
def dictionarykeyFile(keyfile):
    key={}
    with open(keyfile,'r')as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key
def encryptMarksData(datafile, keyfile):
    #construct a dictionary for key data
    key=dictionarykeyFile(keyfile)
    with open(datafile,'r')as f:
        filedata=f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt','w')as f:
        for mark in filedata:
            line=''
            for n in mark:
                line +=key[n]
            f.write(line+'\n')
    return
datafile='DataFiles/marks.txt'
encryptMarksData(datafile, keyfile)

In [19]:
def decryptedMarksData(encryptedfile, keyfile):
    key=dictionarykeyFile(keyfile)
    newkey= {}
    for key,value in key.items():
        newkey[value]=key
    with open(encryptedfile,'r')as f:
        encrypteddata=f.read().split('\n')
    with open('DataFiles/decryptedMarks.txt','w')as f:
        for encryptedmark in encrypteddata:
            line=''
        for n in encryptedmark:
            line +=newkey[n]
            f.write(line+'\n')
    return
encryptedfile='DataFiles/encryptedMarks.txt'
import timeit
st=timeit.default_timer()
decryptedMarksData(encryptedfile,keyfile)
print(timeit.default_timer()-st)

0.001602452000042831


## Python Libraries For Data Science
- Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data. It involves many different disciplines like mathematical and statistical modelling, extracting data from it source and applying data visualization techniques. There are nearly 20 python libraries for Data Science. Top five python libraries are
- TensorFlow
- NumPy
- SciPy
- Pandas
- Matplotlib In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.
## NumPy: (Numerical Python)
- Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion. \Ex: >>import numpy as np
## NumPy Arrays
- NumPy have a fixed size of arrays used to store a collection of elements, unlike python lists. There are three types of arrays called 1D, 2D and 3D arrays.
# Creating 1D and 2D arrays using numPy.

In [21]:

import numpy as np
array_1d = np.array([2,4,5,6,7,9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [22]:
import numpy as np
array_2d = np.array([[2,3,4],[5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In [23]:
import numpy as np
li = [1,2,3,'z']
a = np.array(li)
print(a)

['1' '2' '3' 'z']


In [24]:

import numpy as np
li = [1,2,3,4.0]
a = np.array(li)
a

array([1., 2., 3., 4.])

In [25]:

import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
import numpy as np
a2 = np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [28]:
a2 = np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

# Inspect the structure and Content of array using “ndarrays”
- The most basic object in NumPy is the “ndarray” object or simply an “array”.
- The ndarray has important attributes. They are
- ndarray.ndim: No of dimensions of array referred as “rank”.
- ndarray.shape: Returns the length of the array in tuple.
- ndarray.size: Returns the size of an array.
- ndarray.dtype: We can create or specify “dtype” using standard Python types. - NumPy provides types like numpy.int32, numpy.int16, and numpy.float64
- ndarray.itemsize: Returns the size in bytes of each element in an array
- Create a 2D Array and inspect size, shape, dimensions and dtype of the array.

In [29]:
import numpy as np
array1 = np.random.randint(0,2,size=(3,3,3,3))
array1[2][2][2][1]
print('Shape:',array1.shape)
print('Size:',array1.size)
print('DType:',array1.dtype)
print('ItemSize:',array1.itemsize)
print('Data:',array1.data)

Shape: (3, 3, 3, 3)
Size: 81
DType: int32
ItemSize: 4
Data: <memory at 0x0000016CD457BEB8>


In [30]:
array1 =[[1,2,3,4],[5,6,7,8]]
a1 = np.array(array1)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
print("Shape:",a1.shape)
print("Data Type:",a1.dtype)
print("Size:",a1.size)
print("Dimention:",a1.ndim)

Shape: (2, 4)
Data Type: int32
Size: 8
Dimention: 2


In [32]:
import numpy as np
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [34]:

import numpy as np
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:

b=[[1,2,3],[10,20,30],[11,22,33]]
c=np.array(b)
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

In [36]:
d = c+1
d

array([[ 2,  3,  4],
       [11, 21, 31],
       [12, 23, 34]])

In [37]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(5,11).reshape(2,3)
print(a,)
print(b,'\n')
print(a+b)
print(a/b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]] 

[[ 6  8 10]
 [12 14 16]]
[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [38]:
a = [1,2,3]
a1 = np.array(a)
print(np.sqrt(a1))
print(np.sin(a1))
print(np.cos(a1))
print(np.log(a1))

[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
